### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by peytondmurray**
I made a whole bunch of changes to update the script and make it more usable. Let me know what you think, and I'll rebase to squash the commits.

Code Changes:
* Removed broad exceptions everywhere
* More detailed status messages
* Added option to hide notifications
* `protonvpn` command syntax updated to match latest cli tool
* `protonvpn` commands consolidated into an enum to make future changes easy

Extras:
* Added pre-commit hooks: trailing-whitespace, end-of-file-fixer, check-yaml, check-ast, requirements-txt-fixer, flake8
* Removed unused rule exceptions from .flake8
* Updated README
* Added additional entries to `.gitignore`

### CODE REVIEW

**Comment by gerwalk** [comment]
Great timing -- I just moved over to ProtonVPN from PIA and have spent the morning getting my laptop running Arch set up with it, and found  this project not yet compatible with their new version of the CLI tool. Looking forward to testing this out.

**Comment by peytondmurray** [comment]
> 
> 
> Great timing -- I just moved over to ProtonVPN from PIA and have spent the morning getting my laptop running Arch set up with it, and found this project not yet compatible with their new version of the CLI tool. Looking forward to testing this out.

@gerwalk Same here! My main issue right now is that I want to be able to run protonvpn without superuser privileges, like we did with PIA. Not sure why, but setting the setuid bit doesn't do the job.

**Comment by seadanda** [comment]
Hi @peytondmurray I've just had a read through and this looks really nice! Great to see some interest in this, didn't expect my hacky script to actually get any users. I've actually not been using ProtonVPN as the servers didn't work the entire time I was in China so I defaulted back to PIA instead, but your pull request has made me decide to get back and add some features to this and move to using ProtonVPN.

**Comment by seadanda** [comment]
OK I've just been messing around with it on my system and I have a couple of very small objections/questions:

1. The flake8 ignore E501 (line too long) is a definite requirement, since those warnings are unnecessary and annoying, so I'd vote to reinstate that one. The others I agree, we don't need.

2. Typo in filename requrements.txt -> requirements.txt

3. This is more of a long term consideration but it looks like you've moved to the python-based cli (python-cli-ng), which I'm happy enough to do since it seems to be much faster and better than the incredibly slow bash client, but should we also still support the protonvpn-cli? Extra effort to keep track of, but maybe not that much.

But if you're with me on 1 and 2 then I'm happy to merge!

Last minute edit: I've just seen your last commit removing the "sudo" from the protonvpn calls and saying that the gui needs to be run using sudo. This is actually a non-trivial change. This breaks communication with the notification system, not to mention breaking the rule of using sudo only when you need it, aka not for a status bar icon. So although the passwordless sudo may not be ideal, it is still preferable to using `sudo protonvpn-applet`.

**Comment by peytondmurray** [comment]
>     1. The flake8 ignore E501 (line too long) is a definite requirement, since those warnings are unnecessary and annoying, so I'd vote to reinstate that one. The others I agree, we don't need.

Agreed, long line warnings are annoying. E501 wasn't in the original ignore list, and we have already set `max-line-length = 120`, but I'll add it anyway.

>     2. Typo in filename requrements.txt -> requirements.txt

Just saw you took care of this, thanks!

>     3. This is more of a long term consideration but it looks like you've moved to the python-based cli (python-cli-ng), which I'm happy enough to do since it seems to be much faster and better than the incredibly slow bash client, but should we also still support the protonvpn-cli? Extra effort to keep track of, but maybe not that much.

This would be easy to implement - we can just have separate `Enum` classes for whatever CLI we want. What do you think?

> But if you're with me on 1 and 2 then I'm happy to merge!
> 
> Last minute edit: I've just seen your last commit removing the "sudo" from the protonvpn calls and saying that the gui needs to be run using sudo. This is actually a non-trivial change. This breaks communication with the notification system, not to mention breaking the rule of using sudo only when you need it, aka not for a status bar icon. So although the passwordless sudo may not be ideal, it is still preferable to using `sudo protonvpn-applet`.

This is a really good point about only using `sudo` when we need it - I'll put it back in. How do other VPN clients such as PIA get around asking for a password every time you launch/connect/disconnect the VPN?

**Comment by seadanda** [comment]
> Agreed, long line warnings are annoying. E501 wasn't in the original ignore list, and we have already set max-line-length = 120, but I'll add it anyway.

Yea sorry my bad, I only realised that after I posted the comment. I think the actual reason that my linter was complaining was due to a bad config... the 120 max should have meant that warning didn't show.

> This would be easy to implement - we can just have separate Enum classes for whatever CLI we want. What do you think?

Yes it is really straight forward to implement now, but I was hoping to add some features to this to give it the full functionality of the cli tool, and I guess that we will probably run into problems with some features being available in one, but not the other etc. I'm as yet undecided.

> This is a really good point about only using sudo when we need it - I'll put it back in. How do other VPN clients such as PIA get around asking for a password every time you launch/connect/disconnect the VPN?

PIA just uses plain openvpn config files and piggybacks on a connection manager like NetworkManager/ConnMann etc which avoids the issue, since these connection managers use systemd services which are enabled using root privileges, then controlled through the GUI. Separating the applet into the actual applet and then a backend running as a systemd service with elevated privileges could be something to look into actually.

**Review by seadanda — APPROVED** [review]
Happy to merge

**Pull request merged**
